import type { Metadata } from "next";
import { ResearchPage } from "../research-page";

export const metadata: Metadata = { title: "How to Use a Superbuy Spreadsheet | Sheets Superbuy", description: "A practical start-to-finish method for researching spreadsheet finds, checking product options and preparing an agent order." };

export default function GuidePage() {
  return <ResearchPage label="START HERE / GUIDE · FACT CHECKED AUGUST 2026" title="How to use a Superbuy spreadsheet without guessing" intro="A spreadsheet is most useful as a shortlist—not as proof. This guide separates discovery, order checks, warehouse evidence and parcel decisions so each step has a clear job.">
    <section><p className="article-lead">The fastest workflow is not “find a row and buy immediately.” It is “find, preserve, verify, inspect and then ship.” Each stage catches a different type of mistake.</p></section>
    <section><span className="chapter">01</span><h2>Start with the exact product record</h2><p>Choose a category or search the live index using a useful product description. Open the individual record and confirm that the destination still loads. Marketplace listings can disappear, change seller or replace available options, so a familiar title alone is not enough.</p><div className="check-panel"><strong>Record before ordering</strong><ul><li>Current destination URL</li><li>Selected size, color and version</li><li>Seller size chart or measurements</li><li>Visible price and domestic shipping</li><li>Any restriction or warning shown by the agent</li></ul></div></section>
    <section><span className="chapter">02</span><h2>Understand the two-payment flow</h2><p>Superbuy’s current shopping-agent guide describes two main payment stages. The first covers the item and domestic delivery to the warehouse. The second happens when you submit a parcel for international delivery. That distinction matters: the item price displayed in a spreadsheet is not the final landed cost.</p><p>Before the first payment, estimate international shipping with realistic weight and dimensions. Bulky boxes can increase chargeable weight even when the item itself is light.</p></section>
    <section><span className="chapter">03</span><h2>Wait for warehouse evidence</h2><p>After the purchased item reaches the warehouse, compare its QC photos with the exact option you recorded. Superbuy currently describes three free QC photos in its standard flow, but those images do not remove the buyer’s responsibility to check the item.</p><p>Start with objective mismatches—wrong color, wrong size label, missing component or obvious damage. Then move to category-specific checks such as alignment, measurements, hardware and print placement.</p></section>
    <section><span className="chapter">04</span><h2>Plan the parcel, not just the product</h2><p>When several orders are stored, consolidation can reduce duplicated outer packaging. Superbuy currently states that shopping-agent items can receive 90 days of free storage, giving buyers time to assemble a parcel. Route availability, restrictions and costs can still change by destination and item type.</p><p>Review the selected route, estimated chargeable weight, protection needs, insurance terms and customs responsibilities immediately before submitting the parcel.</p></section>
    <section className="source-panel"><h2>Official references</h2><ul><li><a href="https://www.superbuy.com/en/page/noviceguide/">Superbuy User Guidance</a></li><li><a href="https://www.superbuy.com/en/page/guide/feecomposition/">Fee Composition</a></li><li><a href="https://www.superbuy.com/en/page/guide/transportagent/">Parcel Forwarding Guide</a></li></ul></section><div className="article-end"><strong>Ready to make a shortlist?</strong><p>Browse by category, open the live product record and save the exact option you intend to check.</p><a href="https://kakobuysn.com/AllProducts/">Browse the live index ↗</a></div>
  </ResearchPage>;
}
