import { ResearchPage } from "../research-page";
import { BreadcrumbJsonLd, HowToJsonLd, pageMetadata } from "../seo";

const description = "Plan a Superbuy parcel by separating item cost, chargeable weight, packaging, route availability and customs responsibilities.";
export const metadata = pageMetadata("Superbuy Parcel & Shipping Planner | Sheets Superbuy", description, "/shipping-planner/");

export default function ShippingPage() {
  return <><BreadcrumbJsonLd items={[{name:"Home",path:"/"},{name:"Shipping planner",path:"/shipping-planner/"}]}/><HowToJsonLd name="Plan the parcel before the shipping bill" description={description} path="/shipping-planner/" steps={["Build a landed-cost worksheet","Watch chargeable weight","Use consolidation deliberately","Recheck at submission"]}/><ResearchPage label="PARCEL / PLANNER · FACT CHECKED AUGUST 2026" title="Plan the parcel before the shipping bill" intro="Product price is only the first layer. Use weight, dimensions, packaging and route constraints to avoid treating the cheapest listing as the cheapest delivered choice.">
    <section><p className="article-lead">A useful estimate separates the purchase stage from the international-delivery stage. Superbuy’s official guide currently presents them as two payments, which is why a spreadsheet price should never be described as the final delivered cost.</p></section>
    <section><span className="chapter">01</span><h2>Build a landed-cost worksheet</h2><div className="formula-card"><span>ITEM + DOMESTIC DELIVERY</span><b>+</b><span>AGENT OR OPTIONAL SERVICES</span><b>+</b><span>INTERNATIONAL PARCEL</span><b>+</b><span>POSSIBLE TAX / DUTY</span></div><p>Do not fill uncertain fields with zero. Mark them as estimates and revise after warehouse weighing or packaging.</p></section>
    <section><span className="chapter">02</span><h2>Watch chargeable weight</h2><p>Shipping lines may calculate from actual weight or volumetric weight. A rigid shoe box, large puffer or oversized packaging can occupy more space than its scale weight suggests. This is why two products with similar prices can produce very different parcel costs.</p><div className="check-panel"><strong>Record for each item</strong><ul><li>Estimated actual weight</li><li>Package dimensions when available</li><li>Whether original packaging is essential</li><li>Fragile, liquid, battery or restricted-item context</li><li>Any protection the item genuinely needs</li></ul></div></section>
    <section><span className="chapter">03</span><h2>Use consolidation deliberately</h2><p>Superbuy states that users can store shopping-agent items for 90 days and consolidate orders into one parcel. Consolidation can remove duplicated outer packaging, but one larger parcel is not automatically best for every route, destination or risk tolerance.</p><p>Compare at least two parcel plans when the haul contains bulky or restricted items. Keep fragile pieces away from heavy items unless the protection plan is clear.</p></section>
    <section><span className="chapter">04</span><h2>Recheck at submission</h2><p>Route names, limits, delivery estimates and prices can change. Use the current account calculator at the moment you submit the parcel. Confirm what compensation or insurance covers, and remember that customs assessment remains destination-specific.</p></section>
    <section className="source-panel"><h2>Official references</h2><ul><li><span>Superbuy Fee Composition</span></li><li><span>Shipping Calculator</span></li><li><span>Mailing Restrictions Enquiry</span></li></ul></section><div className="article-end"><strong>Better product research produces better parcel plans.</strong><p>Shortlist items with measurements and packaging in mind.</p><a href="https://kakobuysn.com/AllProducts/" target="_blank" rel="noopener noreferrer">Start a shortlist in the external catalogue ↗</a></div>
  </ResearchPage></>;
}
