import { SiteHeader } from "../site-header";
import { BreadcrumbJsonLd, ItemListJsonLd, absoluteUrl, pageMetadata } from "../seo";
const articles=[
 {slug:"superbuy-product-research-brief",label:"04 · Product research · 12 min",title:"Superbuy product research brief: define the evidence before you compare listings",text:"Primary keyword: Superbuy product research brief. Turn a vague product idea into requirements, evidence fields, stop conditions and an auditable shortlist."},
 {slug:"how-to-use-superbuy-spreadsheet",label:"01 · Buying guide · 14 min",title:"How to use a Superbuy spreadsheet without losing the right product option",text:"Primary keywords: Superbuy spreadsheet, how to use Superbuy. A fact-checked path from discovery to purchase, warehouse inspection and parcel submission."},
 {slug:"superbuy-qc-photo-checklist",label:"02 · QC guide · 13 min",title:"Superbuy QC photo checklist: what to inspect before international shipping",text:"Primary keywords: Superbuy QC photos, Superbuy inspection. A repeatable inspection order grounded in Superbuy’s published warehouse process."},
 {slug:"plan-superbuy-shipping-cost",label:"03 · Shipping guide · 15 min",title:"How to plan Superbuy shipping cost before you build a parcel",text:"Primary keywords: Superbuy shipping cost, Superbuy volumetric weight. A practical model for estimates, packaging, routes and final adjustments."}
];
export const metadata=pageMetadata("Superbuy Guides & Research Articles | Sheets Superbuy","Independent guides to Superbuy product research, spreadsheet use, QC photo review and international parcel planning.","/articles/");
 export default function Articles(){return <main><BreadcrumbJsonLd items={[{name:"Home",path:"/"},{name:"Articles",path:"/articles/"}]}/><ItemListJsonLd name="Independent Superbuy research articles" path="/articles/" items={articles.map(x=>({name:x.title,url:absoluteUrl(`/articles/${x.slug}/`)}))}/><SiteHeader/><section className="directory-shell"><p className="eyebrow">Research library · Fact checked September 2026</p><h1>Independent Superbuy guides.</h1><p className="directory-intro">Start with a product research brief, then use the established guides for the shopping-agent workflow, warehouse evidence and shipping planning. Each article separates current platform facts from independent decision methods.</p><div className="article-card-grid">{articles.map(x=><a className="article-card" href={`/articles/${x.slug}/`} key={x.slug}><small>{x.label}</small><h2>{x.title}</h2><p>{x.text}</p><span>Read full article ↗</span></a>)}</div><div className="fact-note article-roadmap"><strong>Next product-research topics</strong><p>Category match → listing identity → title, image and option consistency → seller comparison → variant and size evidence → shortlists by product type.</p><a href="/faq/">Check the FAQ ↗</a></div></section></main>}
