import type { Metadata } from "next";
import { ResearchPage } from "../research-page";

export const metadata: Metadata = { title: "Superbuy QC Photo Checklist | Sheets Superbuy", description: "Use this practical QC checklist to inspect spreadsheet finds after they arrive at the agent warehouse." };

export default function QCPage() {
  return <ResearchPage label="EVIDENCE / QC · FACT CHECKED AUGUST 2026" title="A QC checklist built around decisions" intro="QC photos are useful when you know what question each image should answer. Check objective order accuracy first, then category-specific details.">
    <section><p className="article-lead">Treat QC photos as warehouse evidence, not a quality guarantee. The most important first question is whether the warehouse received the same option that you ordered.</p></section>
    <section><span className="chapter">01</span><h2>Confirm the order basics</h2><div className="check-panel"><strong>Always check first</strong><ul><li>Correct product type and visible color</li><li>Size label matches the order</li><li>Requested quantity and included pieces</li><li>No obvious tears, stains, cracks or crushed areas</li><li>Packaging matches any requirement that matters to you</li></ul></div><p>If an angle does not show the detail you need, do not infer it from a distant overview. Request an additional image or measurement when that option is available.</p></section>
    <section><span className="chapter">02</span><h2>Use category-specific checks</h2><h3>Shoes</h3><p>Compare both shoes together. Look at shape, symmetry, visible glue, stitching, sole alignment and the size labels. If fit is critical, an insole measurement is more useful than relying only on the printed size.</p><h3>Clothing</h3><p>Check garment measurements against a familiar item measured in the same way. Inspect print position, embroidery, seam alignment and any missing hardware. Lighting can change color, so avoid judging a subtle shade from one photo alone.</p><h3>Bags and accessories</h3><p>Inspect closures, zippers, handles, edges, hardware and included straps. Ask for a clear image of any detail that affects function, not just appearance.</p></section>
    <section><span className="chapter">03</span><h2>Choose an action</h2><p>Finish each review with one of three outcomes: accept, ask for more evidence, or contact the agent about a return or exchange. Avoid an endless “maybe” state. Your notes should say exactly which detail caused the decision.</p><div className="decision-grid"><div><strong>Accept</strong><p>The option matches and the visible condition is acceptable.</p></div><div><strong>Verify</strong><p>A missing angle or measurement prevents a decision.</p></div><div><strong>Resolve</strong><p>A clear mismatch or defect needs agent support.</p></div></div></section>
    <section className="source-panel"><h2>Official references</h2><ul><li><a href="https://www.superbuy.com/en/page/guide/shoppingagent/">Shopping Agent Guide</a></li><li><a href="https://www.superbuy.com/en/page/newguide/transportagent/">Forwarding and inspection guidance</a></li></ul></section><div className="article-end"><strong>Find something worth checking.</strong><p>Start with a live product record, then keep this checklist for warehouse arrival.</p><a href="https://kakobuysn.com/AllProducts/">Open product records ↗</a></div>
  </ResearchPage>;
}
